spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
        - id: auth_route
          uri: lb://backend
#         설명 - lb: 로드밸런서 의미, 실제 프로토콜 의미 x, 실제로는 http 또는 https 사용
#         설명 - backend: 로드밸런서가 인식하는 논리적 이름
          predicates:
            - Path=/api/auth/**
#          설명 - api/auth로 시작하는 url 에 작업 처리
          filters:
            - name: JwtAuthenticationFilter
#           해당 url 요청를 jwt 필터
        - id: public_route
          uri: lb://backend
          predicates:
            - Path=/api/public/**
    loadbalancer:
      instances:
#       로드밸런서 대상
        backend:
          - http://localhost:8080
#          - http://localhost:8081
#          - http://localhost:8082
#          일단 싱글 서버로 진행
server:
  port: 9090

jwt:
  secret: mySecretKey