spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
        - id: load_balanced_route
          uri: lb://backend
#         lb: 로드밸런서 의미, 실제 프로토콜 의미 x, 실제로는 http 또는 https 사용
#         backend: 로드밸런서가 인식하는 논리적 이름
          predicates:
            - Path=/api/**
#           api로 시작하는 url 에 작업 처리
#
#          filters:
#            - StripPrefix=1
#            filters 역할: path명 중 접두사 (api) 제거
#
    loadbalancer:
      instances:
        backend:
          - http://localhost:8080
#          - http://localhost:8081
#          - http://localhost:8082
#          일단 싱글 서버로 진행
server:
  port: 9090
